<?php

namespace Web\WebBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Web\WebBundle\Controller\PostreController();
        return $instance;
    }
}
