Web\WebBundle\Entity\Postre:
  type: entity
  table: postre
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    price:
      type: float
    foto:
      type: string
      length: 500
    foto_thumb:
      type: string
      length: 500